hosts:
  - name: 192.168.1.101
    username: student
    password: Meilab123
    port: 22
    cmd: "show running-config"
    type: cisco_ios
    hostname: R1
    ospf_id: 150.1.1.1
    interfaces:
      - name: loopback0
        ipv4_addr: 150.1.1.1
        ipv4_mask: 255.255.255.255
      - name: GigabitEthernet1
        is_sub: true
        subinterfaces:
        - name: GigabitEthernet1.14
          vlan: 14
          ipv4_addr: 155.1.14.1
          ipv4_mask: 255.255.255.0
        - name: GigabitEthernet1.13
          vlan: 13
          ipv4_addr: 155.1.13.1
          ipv4_mask: 255.255.255.0
        - name: GigabitEthernet1.12
          vlan: 12
          ipv4_addr: 155.1.12.1
          ipv4_mask: 255.255.255.0
    networks:
      - 155.1.14.1
      - 155.1.13.1
      - 155.1.12.1
      - 150.1.1.1
    
  - name: 192.168.1.102
    username: student
    password: Meilab123
    port: 22
    cmd: "show running-config"
    type: cisco_ios
    hostname: R2
    ospf_id: 150.1.2.2
    interfaces:
      - name: loopback0
        ipv4_addr: 150.1.2.2
        ipv4_mask: 255.255.255.255
      - name: GigabitEthernet1
        is_sub: true
        subinterfaces:
        - name: GigabitEthernet1.12
          vlan: 12
          ipv4_addr: 155.1.12.2
          ipv4_mask: 255.255.255.0
    networks:
      - 155.1.12.1
      - 150.1.2.2
    
  - name: 192.168.1.103
    username: student
    password: Meilab123
    port: 22
    cmd: "show running-config"
    type: cisco_ios
    hostname: R3
    ospf_id: 150.1.3.3
    interfaces:
      - name: loopback0
        ipv4_addr: 150.1.3.3
        ipv4_mask: 255.255.255.255
      - name: GigabitEthernet1
        is_sub: true
        subinterfaces:
        - name: GigabitEthernet1.13
          vlan: 13
          ipv4_addr: 155.1.13.3
          ipv4_mask: 255.255.255.0
    networks:
      - 155.1.13.3
      - 150.1.3.3
    
  - name: 192.168.1.104
    username: student
    password: Meilab123
    port: 22
    cmd: "show running-config"
    type: cisco_ios
    hostname: R4
    ospf_id: 150.1.4.4
    interfaces:
      - name: loopback0
        ipv4_addr: 150.1.4.4
        ipv4_mask: 255.255.255.255
      - name: GigabitEthernet1
        is_sub: true
        subinterfaces:
        - name: GigabitEthernet1.14
          vlan: 14
          ipv4_addr: 155.1.14.4
          ipv4_mask: 255.255.255.0
    networks:
      - 155.1.14.4
      - 150.1.4.4
    
